version: "3"

services:
  frontend:
    container_name: shikaku_frontend
    build: .
    tty: true
    ports:
      - "8000:3000"
    volumes:
      - .:/shikaku
    command: bash -c "npm install & npm run dev"